### ISSUE TITLE
can't get next page of timeline

### ISSUE THREAD

**Issue by mehhrad** [charlieAndroidDev/Instagram4Android#10]
thanks for update but pagination seems to not work

`InstagramFeedResult result = insta.sendRequest(new InstagramTimelineFeedRequest());
            System.out.println(result);
            result = insta.sendRequest(new InstagramTimelineFeedRequest(result.getNext_max_id()));
            System.out.println("new result = " + result);`

i get the first result successfully but for second result it throws an parse exception:

`com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
W:  at [Source: <!DOCTYPE html>
...
W:     <head><meta charset="utf-8">
W:         <meta http-equiv="X-UA-Compatible" content="IE=edge">
W:         <title>
W:                   Page Not Found &bull; Instagram
W:                 </title>
... `

**Comment by charlieAndroidDev** [comment]
Yeah my testing was minimal, I'll have a closer look at the php implementation and try and have a fix for you.

**Comment by mehhrad** [comment]
thank you sir :)

**Comment by charlieAndroidDev** [comment]
It should be fixed now, look at the InstagramAndroidTest.java file for usage.

**Comment by mehhrad** [comment]
i get this exception running your own Test class : /

```
I/TestRunner: java.lang.NoSuchMethodError: No static method encodeBase64String([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
                  at dev.niekirk.com.instagram4android.requests.InstagramTimelineFeedRequest.createRequest(InstagramTimelineFeedRequest.java:75)
                  at dev.niekirk.com.instagram4android.requests.InstagramTimelineFeedRequest.execute(InstagramTimelineFeedRequest.java:46)
                  at dev.niekirk.com.instagram4android.requests.InstagramTimelineFeedRequest.execute(InstagramTimelineFeedRequest.java:26)
                  at dev.niekirk.com.instagram4android.Instagram4Android.sendRequest(Instagram4Android.java:195)
                  at semycolon.mehrad.instasubmarine.TstTimeLine.fixesImplementedCorrectly(TstTimeLine.java:99)
                  at java.lang.reflect.Method.invoke(Native Method)
                  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
                  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
                  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
                  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
                  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
                  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
                  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
                  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                  at org.junit.runners.Suite.runChild(Suite.java:128)
                  at org.junit.runners.Suite.runChild(Suite.java:27)
                  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                  at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
                  at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
                  at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
                  at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
                  at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1960)
I/TestRunner: ----- end exception -----
```

**Comment by charlieAndroidDev** [comment]
Use the latest release and don't run it in a unit test.  The android.Base64 class doesn't have an implementation on your computers JVM but it does on a virtual (or real) android device.

**Comment by mehhrad** [comment]
i moved to v 0.1.15 and got another exception.

```
Caused by: java.lang.IllegalArgumentException: Unexpected char 0x0a at 20 in X-IG-INSTALLED-APPS value: eyIxIjowLCIyIjowfQ==
                  
                      at okhttp3.Headers$Builder.checkNameAndValue(Headers.java:321)
                      at okhttp3.Headers$Builder.set(Headers.java:301)
                      at okhttp3.Request$Builder.header(Request.java:165)
                      at dev.niekirk.com.instagram4android.requests.InstagramTimelineFeedRequest.createRequest(InstagramTimelineFeedRequest.java:75)
                      at dev.niekirk.com.instagram4android.requests.InstagramTimelineFeedRequest.execute(InstagramTimelineFeedRequest.java:46)
                      at dev.niekirk.com.instagram4android.requests.InstagramTimelineFeedRequest.execute(InstagramTimelineFeedRequest.java:26)
                      at dev.niekirk.com.instagram4android.Instagram4Android.sendRequest(Instagram4Android.java:195)
                      at semycolon.mehrad.instasubmarine.mvp.screen.main.MainActivity.lambda$runTest$2$MainActivity(MainActivity.java:112)
                      at semycolon.mehrad.instasubmarine.mvp.screen.main.MainActivity$$Lambda$2.apply(Unknown Source)
                      at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
                      at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200) 
                      at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252) 
                      at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61) 
                      at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52) 
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                      at java.lang.Thread.run(Thread.java:761) 
```

**Comment by charlieAndroidDev** [comment]
As I said, please use the latest version which is v0.1.18

This will fix that issue.

**Comment by charlieAndroidDev** [comment]
Ok, that was a small issue I'd overlooked.  Please use v0.1.20 and call ```getItems()``` now instead.
