### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by rasoolta** [charlieAndroidDev/Instagram4Android#17]
hi
when i login with your api, i get error and vm is shutdown 
error for this line : Response response = this.api.getClient().newCall(request).execute();
i use min sdk 21 and use internet permision in manifest 
how to fix this
tnx

**Comment by rasoolta** [comment]
error

12-10 18:34:43.944 3649-3649/? I/art: Not late-enabling -Xcheck:jni (already on)
12-10 18:34:43.971 3649-3654/? E/art: Failed sending reply to debugger: Broken pipe
12-10 18:34:43.971 3649-3654/? I/art: Debugger is no longer active
12-10 18:34:44.004 3649-3649/? W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=x86 --instruction-set-features=smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=x86 --instruction-set-features=default --dex-file=/data/app/com.example.rasoolta.myapplication-1/split_lib_dependencies_apk.apk --oat-file=/data/dalvik-cache/x86/data@app@com.example.rasoolta.myapplication-1@split_lib_dependencies_apk.apk@classes.dex) because non-0 exit status
12-10 18:34:44.188 3649-3649/? W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=x86 --instruction-set-features=smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=x86 --instruction-set-features=default --dex-file=/data/app/com.example.rasoolta.myapplication-1/split_lib_slice_0_apk.apk --oat-file=/data/dalvik-cache/x86/data@app@com.example.rasoolta.myapplication-1@split_lib_slice_0_apk.apk@classes.dex) because non-0 exit status
12-10 18:34:44.215 3649-3649/? W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=x86 --instruction-set-features=smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=x86 --instruction-set-features=default --dex-file=/data/app/com.example.rasoolta.myapplication-1/split_lib_slice_1_apk.apk --oat-file=/data/dalvik-cache/x86/data@app@com.example.rasoolta.myapplication-1@split_lib_slice_1_apk.apk@classes.dex) because non-0 exit status
12-10 18:34:44.228 3649-3649/? W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=x86 --instruction-set-features=smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=x86 --instruction-set-features=default --dex-file=/data/app/com.example.rasoolta.myapplication-1/split_lib_slice_2_apk.apk --oat-file=/data/dalvik-cache/x86/data@app@com.example.rasoolta.myapplication-1@split_lib_slice_2_apk.apk@classes.dex) because non-0 exit status
12-10 18:34:44.248 3649-3649/? W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=x86 --instruction-set-features=smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=x86 --instruction-set-features=default --dex-file=/data/app/com.example.rasoolta.myapplication-1/split_lib_slice_3_apk.apk --oat-file=/data/dalvik-cache/x86/data@app@com.example.rasoolta.myapplication-1@split_lib_slice_3_apk.apk@classes.dex) because non-0 exit status
12-10 18:34:44.262 3649-3649/? W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=x86 --instruction-set-features=smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=x86 --instruction-set-features=default --dex-file=/data/app/com.example.rasoolta.myapplication-1/split_lib_slice_4_apk.apk --oat-file=/data/dalvik-cache/x86/data@app@com.example.rasoolta.myapplication-1@split_lib_slice_4_apk.apk@classes.dex) because non-0 exit status
12-10 18:34:44.277 3649-3649/? W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=x86 --instruction-set-features=smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=x86 --instruction-set-features=default --dex-file=/data/app/com.example.rasoolta.myapplication-1/split_lib_slice_5_apk.apk --oat-file=/data/dalvik-cache/x86/data@app@com.example.rasoolta.myapplication-1@split_lib_slice_5_apk.apk@classes.dex) because non-0 exit status
12-10 18:34:44.291 3649-3649/? W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=x86 --instruction-set-features=smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=x86 --instruction-set-features=default --dex-file=/data/app/com.example.rasoolta.myapplication-1/split_lib_slice_6_apk.apk --oat-file=/data/dalvik-cache/x86/data@app@com.example.rasoolta.myapplication-1@split_lib_slice_6_apk.apk@classes.dex) because non-0 exit status
12-10 18:34:44.306 3649-3649/? W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=x86 --instruction-set-features=smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=x86 --instruction-set-features=default --dex-file=/data/app/com.example.rasoolta.myapplication-1/split_lib_slice_7_apk.apk --oat-file=/data/dalvik-cache/x86/data@app@com.example.rasoolta.myapplication-1@split_lib_slice_7_apk.apk@classes.dex) because non-0 exit status
12-10 18:34:44.320 3649-3649/? W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=x86 --instruction-set-features=smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=x86 --instruction-set-features=default --dex-file=/data/app/com.example.rasoolta.myapplication-1/split_lib_slice_8_apk.apk --oat-file=/data/dalvik-cache/x86/data@app@com.example.rasoolta.myapplication-1@split_lib_slice_8_apk.apk@classes.dex) because non-0 exit status
12-10 18:34:44.334 3649-3649/? W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=x86 --instruction-set-features=smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=x86 --instruction-set-features=default --dex-file=/data/app/com.example.rasoolta.myapplication-1/split_lib_slice_9_apk.apk --oat-file=/data/dalvik-cache/x86/data@app@com.example.rasoolta.myapplication-1@split_lib_slice_9_apk.apk@classes.dex) because non-0 exit status
12-10 18:34:44.336 3649-3649/? I/InstantRun: starting instant run server: is main process
12-10 18:34:44.388 3649-3649/? W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
12-10 18:34:44.676 3649-3649/? D/AndroidRuntime: Shutting down VM
12-10 18:34:44.677 3649-3649/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.example.rasoolta.myapplication, PID: 3649
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.rasoolta.myapplication/com.example.rasoolta.myapplication.MainActivity}: android.os.NetworkOnMainThreadException
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                  Caused by: android.os.NetworkOnMainThreadException
                                                     at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1273)
                                                     at java.net.InetAddress.lookupHostByName(InetAddress.java:431)
                                                     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
                                                     at java.net.InetAddress.getAllByName(InetAddress.java:215)
                                                     at okhttp3.Dns$1.lookup(Dns.java:39)
                                                     at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:171)
                                                     at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:137)
                                                     at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:82)
                                                     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:171)
                                                     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
                                                     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
                                                     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
                                                     at okhttp3.RealCall.execute(RealCall.java:69)
                                                     at dev.niekirk.com.instagram4android.requests.InstagramGetRequest.execute(InstagramGetRequest.java:36)
                                                     at dev.niekirk.com.instagram4android.Instagram4Android.sendRequest(Instagram4Android.java:195)
                                                     at dev.niekirk.com.instagram4android.Instagram4Android.getOrFetchCsrf(Instagram4Android.java:164)
                                                     at dev.niekirk.com.instagram4android.Instagram4Android.login(Instagram4Android.java:132)
                                                     at com.example.rasoolta.myapplication.MainActivity.onCreate(MainActivity.java:19)
                                                     at android.app.Activity.performCreate(Activity.java:6237)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
12-10 18:39:44.744 3649-3649/? I/Process: Sending signal. PID: 3649 SIG: 9

**Comment by rasoolta** [comment]
```
12-10 18:34:43.944 3649-3649/? I/art: Not late-enabling -Xcheck:jni (already on)
12-10 18:34:43.971 3649-3654/? E/art: Failed sending reply to debugger: Broken pipe
12-10 18:34:43.971 3649-3654/? I/art: Debugger is no longer active
12-10 18:34:44.004 3649-3649/? W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=x86 --instruction-set-features=smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=x86 --instruction-set-features=default --dex-file=/data/app/com.example.rasoolta.myapplication-1/split_lib_dependencies_apk.apk --oat-file=/data/dalvik-cache/x86/data@app@com.example.rasoolta.myapplication-1@split_lib_dependencies_apk.apk@classes.dex) because non-0 exit status
12-10 18:34:44.188 3649-3649/? W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=x86 --instruction-set-features=smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=x86 --instruction-set-features=default --dex-file=/data/app/com.example.rasoolta.myapplication-1/split_lib_slice_0_apk.apk --oat-file=/data/dalvik-cache/x86/data@app@com.example.rasoolta.myapplication-1@split_lib_slice_0_apk.apk@classes.dex) because non-0 exit status
12-10 18:34:44.215 3649-3649/? W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=x86 --instruction-set-features=smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=x86 --instruction-set-features=default --dex-file=/data/app/com.example.rasoolta.myapplication-1/split_lib_slice_1_apk.apk --oat-file=/data/dalvik-cache/x86/data@app@com.example.rasoolta.myapplication-1@split_lib_slice_1_apk.apk@classes.dex) because non-0 exit status
12-10 18:34:44.228 3649-3649/? W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=x86 --instruction-set-features=smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=x86 --instruction-set-features=default --dex-file=/data/app/com.example.rasoolta.myapplication-1/split_lib_slice_2_apk.apk --oat-file=/data/dalvik-cache/x86/data@app@com.example.rasoolta.myapplication-1@split_lib_slice_2_apk.apk@classes.dex) because non-0 exit status
12-10 18:34:44.248 3649-3649/? W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=x86 --instruction-set-features=smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=x86 --instruction-set-features=default --dex-file=/data/app/com.example.rasoolta.myapplication-1/split_lib_slice_3_apk.apk --oat-file=/data/dalvik-cache/x86/data@app@com.example.rasoolta.myapplication-1@split_lib_slice_3_apk.apk@classes.dex) because non-0 exit status
12-10 18:34:44.262 3649-3649/? W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=x86 --instruction-set-features=smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=x86 --instruction-set-features=default --dex-file=/data/app/com.example.rasoolta.myapplication-1/split_lib_slice_4_apk.apk --oat-file=/data/dalvik-cache/x86/data@app@com.example.rasoolta.myapplication-1@split_lib_slice_4_apk.apk@classes.dex) because non-0 exit status
12-10 18:34:44.277 3649-3649/? W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=x86 --instruction-set-features=smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=x86 --instruction-set-features=default --dex-file=/data/app/com.example.rasoolta.myapplication-1/split_lib_slice_5_apk.apk --oat-file=/data/dalvik-cache/x86/data@app@com.example.rasoolta.myapplication-1@split_lib_slice_5_apk.apk@classes.dex) because non-0 exit status
12-10 18:34:44.291 3649-3649/? W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=x86 --instruction-set-features=smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=x86 --instruction-set-features=default --dex-file=/data/app/com.example.rasoolta.myapplication-1/split_lib_slice_6_apk.apk --oat-file=/data/dalvik-cache/x86/data@app@com.example.rasoolta.myapplication-1@split_lib_slice_6_apk.apk@classes.dex) because non-0 exit status
12-10 18:34:44.306 3649-3649/? W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=x86 --instruction-set-features=smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=x86 --instruction-set-features=default --dex-file=/data/app/com.example.rasoolta.myapplication-1/split_lib_slice_7_apk.apk --oat-file=/data/dalvik-cache/x86/data@app@com.example.rasoolta.myapplication-1@split_lib_slice_7_apk.apk@classes.dex) because non-0 exit status
12-10 18:34:44.320 3649-3649/? W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=x86 --instruction-set-features=smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=x86 --instruction-set-features=default --dex-file=/data/app/com.example.rasoolta.myapplication-1/split_lib_slice_8_apk.apk --oat-file=/data/dalvik-cache/x86/data@app@com.example.rasoolta.myapplication-1@split_lib_slice_8_apk.apk@classes.dex) because non-0 exit status
12-10 18:34:44.334 3649-3649/? W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=x86 --instruction-set-features=smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=x86 --instruction-set-features=default --dex-file=/data/app/com.example.rasoolta.myapplication-1/split_lib_slice_9_apk.apk --oat-file=/data/dalvik-cache/x86/data@app@com.example.rasoolta.myapplication-1@split_lib_slice_9_apk.apk@classes.dex) because non-0 exit status
12-10 18:34:44.336 3649-3649/? I/InstantRun: starting instant run server: is main process
12-10 18:34:44.388 3649-3649/? W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
12-10 18:34:44.676 3649-3649/? D/AndroidRuntime: Shutting down VM
12-10 18:34:44.677 3649-3649/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.example.rasoolta.myapplication, PID: 3649
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.rasoolta.myapplication/com.example.rasoolta.myapplication.MainActivity}: android.os.NetworkOnMainThreadException
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                  Caused by: android.os.NetworkOnMainThreadException
                                                     at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1273)
                                                     at java.net.InetAddress.lookupHostByName(InetAddress.java:431)
                                                     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
                                                     at java.net.InetAddress.getAllByName(InetAddress.java:215)
                                                     at okhttp3.Dns$1.lookup(Dns.java:39)
                                                     at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:171)
                                                     at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:137)
                                                     at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:82)
                                                     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:171)
                                                     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
                                                     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
                                                     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
                                                     at okhttp3.RealCall.execute(RealCall.java:69)
                                                     at dev.niekirk.com.instagram4android.requests.InstagramGetRequest.execute(InstagramGetRequest.java:36)
                                                     at dev.niekirk.com.instagram4android.Instagram4Android.sendRequest(Instagram4Android.java:195)
                                                     at dev.niekirk.com.instagram4android.Instagram4Android.getOrFetchCsrf(Instagram4Android.java:164)
                                                     at dev.niekirk.com.instagram4android.Instagram4Android.login(Instagram4Android.java:132)
                                                     at com.example.rasoolta.myapplication.MainActivity.onCreate(MainActivity.java:19)
                                                     at android.app.Activity.performCreate(Activity.java:6237)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
12-10 18:39:44.744 3649-3649/? I/Process: Sending signal. PID: 3649 SIG: 9``
```

**Comment by charlieAndroidDev** [comment]
You are trying to login on the UI thread.  Please use rxJava or AsyncTask to use this library on a background thread.

**Comment by QUIQUELHAPPY** [comment]
could you post an example on using asynctask with this library? I've this code right now but I'm not sure how to execute it using async task

```
fun executeInstagramLogin(username: String, password: String){
    val instagram = Instagram4Android.builder().username(username).password(password).build()
    instagram.setup()
    instagram.login()
}
```
*btw this code is written in kotlin
