### ISSUE TITLE
How to post video

### ISSUE THREAD

**Issue by comtong** [charlieAndroidDev/Instagram4Android#7]
post video seem not update

**Comment by charlieAndroidDev** [comment]
I'll take a look at this soon, thanks for reporting.

**Comment by FedericoPonzi** [comment]
Hello,
While trying to upload a video, I get this:

FATAL EXCEPTION: AsyncTask #3
    Process: me.fponzi.instantsharing, PID: 16226
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:353)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NullPointerException
        at java.io.FileOutputStream.<init>(FileOutputStream.java:212)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
        at dev.niekirk.com.instagram4android.requests.InstagramUploadVideoRequest.configureThumbnail(InstagramUploadVideoRequest.java:105)
        at dev.niekirk.com.instagram4android.requests.InstagramUploadVideoRequest.execute(InstagramUploadVideoRequest.java:84)
        at dev.niekirk.com.instagram4android.requests.InstagramUploadVideoRequest.execute(InstagramUploadVideoRequest.java:33)
        at dev.niekirk.com.instagram4android.Instagram4Android.sendRequest(Instagram4Android.java:241)
        at me.fponzi.instantsharing.utils.InstagramAPIWrapper$PostVideoAsyncTask.doInBackground(InstagramAPIWrapper.java:129)
        at me.fponzi.instantsharing.utils.InstagramAPIWrapper$PostVideoAsyncTask.doInBackground(InstagramAPIWrapper.java:108)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 

This is my code:
```
  public class PostVideoAsyncTask extends AsyncTask<String, Void, StatusResult>
    {
        public final String TAG = PostVideoAsyncTask.class.getCanonicalName();
        private final File video;
        private final ShareDoneCallback callback;

        public PostVideoAsyncTask(File video, ShareDoneCallback callback)
        {
            this.video = video;
            this.callback = callback;
        }
    
        @Override
        protected StatusResult doInBackground(String... strings)
        {
            try
            {

                Log.i(TAG, "doInBackground: " + (instagram == null));
                return instagram.sendRequest(new InstagramUploadVideoRequest( // line 129
                                    video,
                            Config.CAPTION)); 
    
            }
            catch (IOException e)
            {
                Log.e(TAG, "doInBackground: login error:", e );
                e.printStackTrace();
            }
            return null;
        }
    
        @Override
        protected void onPostExecute(StatusResult statusResult)
        {
            callback.sharedDoneCallback(statusResult.getStatus().equals("ok"));
        }
    }
```

Any suggestions? Thanks!

**Comment by FedericoPonzi** [comment]
The problem is that at line 100 in InstagramUploadVideoRequest, there is this:

    FileOutputStream fos = new FileOutputStream(this.thumbnailFile);

but `this.thumbnailFile` is null.

**Comment by FedericoPonzi** [comment]
I've  managed fix that, but now I'm stuck with this error:

```
Result: InstagramConfigurePhotoResult(super=StatusResult(super=dev.niekirk.com.instagram4android.requests.payload.InstagramConfigurePhotoResult@3a6bd1b, status=fail, message=Transcode not finished yet.), media=null, upload_id=null)
```

at this line:

```
configurePhotoResult = this.api
                            .sendRequest(new InstagramConfigurePhotoRequest(
                                    this.fileToBitmap(this.imageFile), this.uploadId, this.caption));
                    Log.d("UPLOAD", "Result: " + configurePhotoResult);
```
Any ideas on how to fix this? Thanks

**Comment by FedericoPonzi** [comment]
The problem is with InstagramConfigurePhotoRequest, which is still STUB. Instead of throwing a runtime exception ("stub"), returning an "ERROR" status, you choose to return Status "ok", wasting 2 days of mine. Thanks anyway
